CREATE DATABASE nys_history;

CREATE TABLE places(
  name char(128) NOT NULL,
  county char(64) NOT NULL,
  registered date NOT NULL,
  national_number char(64) NOT NULL,
  long decimal(11) NOT NULL,
  lat decimal(11) NOT NULL,
  loc char(64) NOT NULL,
  id SERIAL PRIMARY KEY
);

COPY places(name, county, registered, national_number, long, lat, loc)
FROM '/Users/mattlucas/dev/nys_historic_app/data/National_Register_of_Historic_Places.csv' DELIMITER ';' CSV;